### ISSUE TITLE
Multilevel Logistic Regressions with Python: A Nightmare

### ISSUE THREAD

**Issue by samuelmull** [Neuroling/SPINCO_SINEEG#4]
I am writing this down partially to document the issue, partially because I hope it will help me think of a solution if I think it through again.

## Current state & outline of the issue
Most recent commit: [f4d9448](https://github.com/Neuroling/SPINCO_SINEEG/commit/f4d9448b12b8cb8a548547862e8f34d1d758ab6f)
Mostly concerning the script located at [Permalink](https://github.com/Neuroling/SPINCO_SINEEG/blob/f4d9448b12b8cb8a548547862e8f34d1d758ab6f/Analysis/SiN/EEG/3_analysis_SMeier/sketch_PreStim_writing.py)
Currently, we have a "working" version of the logistic regression using the statsmodels package, with one big flaw: It does not account for multilevel/hierarchical data. Since our data is repeated measures, we need to be able to account for that by using subjectID as a grouping variable. Here are some other things I tried, but ultimately failed:

## Using sklearn
I considered following [this guide](https://www.statology.org/logistic-regression-python/) and using the [logistic regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) of scikit-learn. However, this also does not account for multilevel data. Furthermore, I had some issues with the categorical independent variables (IVs) using this function.

## Using R in python
I found out that if I export the dataframe on which the model should be run as a .csv and import it into R, I can run the multilevel logistic regression without any problem using `glmer` from the `lme4` package (using RStudio on my own laptop, not the virtual machine) - see code here [(Permalink)](https://github.com/Neuroling/SPINCO_SINEEG/blob/f4d9448b12b8cb8a548547862e8f34d1d758ab6f/Analysis/SiN/EEG/3_analysis_SMeier/PreStim_logitRegression.R).
Unfortunately, we cannot simply run the model in R instead of python. Apart from running the model, the python script handles critical things like  the separation of the data into NV & SSN, the random-subsampling procedure to equalise counts of correct and incorrect trials, the iteration-process, the loops to run the model for every timeframe and every channel separately (requiring the creation of a separate dataframe with every loop - a total of [n_channels * n_timeframes * n_iterations] dataframes), and the accumulation of outputs across iterations. I can theoretically translate that into R, but I would rather not - it would take a lot of time, and I am not as experienced in R.
So I tried to use the two ways I could find to run the `glmer` function in python.

### pymer4
[pymer4](https://eshinjolly.com/pymer4/index.html) is a great package that promises to act as a wrapper around R's `lme4`. It requires both R's `lme4` package as well as python's `rpy2` package, which works as an interface between R and python - in other words, it allows to use python with an R backend.
Unfortunately, the import of the needed `lmer` function from the `pymer4` package failed. My guess is that it is a circular import dependency issue, but I do not know how to fix that, nor if it is an issue on my end or by the `pymer4` package. I opened an [issue report](https://github.com/ejolly/pymer4/issues/135) on the pymer4 github yesterday.

### rpy2
I thought that if `pymer4` did not work out, why not directly use `rpy2`? Especially since the R-package `lme4` was already installed as a dependency for `pymer4`.
Attempting to run the model gave me the following error:
`RRuntimeError: Error in initializePtr() :   function 'chm_factor_ldetL2' not provided by package 'Matrix'`
Which, I found out [here](https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack), might be due to the version of R's `Matrix` package being incompatible with binary data. The thread linked before also proposes that updating the `lme4` package to the [newest version, 1.1-35.1](https://cran.r-project.org/web/packages/lme4/index.html) would do the trick. 
Unfortunately, updating the `lme4` package using `rpy2` gives the following error:
`ERROR: compilation failed for package lme4`
After this, it reverts to the previous version (1.1-34).
I tried following the answers to similar questions, [here](https://stackoverflow.com/questions/71058872/trouble-installing-lme4-package-in-r) and [here](https://stackoverflow.com/questions/75838035/cant-install-gmm-package-in-r-ubuntu-22-04):
In the ubuntu terminal:
` sudo docker run -rm -ti eddelbuettel/r2u:20.04` to go to an R console, then running `system.time(install.packages("lme4"))` - which does work.
But then activating the `pymer4-mne` conda environment, which is where `rpy2` is installed, and then calling `conda list`, will still list `r-lme4     1.1-34` - I'm guessing, because the above solution would work when directly using R or RStudio, but not the `rpy2` package.

## Using R in R
I finally gave up on trying to make it work in python, with or without R backend. I thought, if nothing else works, I might as well use the R-code documented above... in R! (groundbreaking, I know)
I have outlined previously why I would really much rather not do this, but I thought I might be able find a way to procedurally create the [n_channels * n_timeframes * n_iterations] dataframes in python and execute the R script alongside, thinking I'd cross that bridge when I got there. 
I did not get there. I am unable to install RStudio on the virtual machine (see screenshot below), and I cannot process that many dataframes or run this many models on my personal laptop with its cutting-edge 8GB of RAM. 

![Screenshot 2024-03-07 151425](https://github.com/Neuroling/SPINCO_SINEEG/assets/108412416/629e4186-7e63-4e5a-a119-47bcdf77b754)

**Comment by gorkafraga** [comment]
I take that your are trying to predict Correct/incorrect based on EEG and degradation level?

Is it not possible to do that in Statsmodel? 
https://www.andrewvillazon.com/logistic-regression-python-statsmodels/#fitting-a-logistic-regression

I would also give up on hybrid solutions of R fromb python. I am convinced they should be a way of analyzing this on a python and i also failed with  those packages. 

[Not preferred:] If R is the only way , maybe just running R code (no R studio) from the VM (after local test on R studio)

**Comment by samuelmull** [comment]
@gorkafraga yes, exactly! This is the "accuracy ~ eeg_data * degradation_levels + word_position" thing.

The most recent "working" version of the logistic regression is using `statsmodels` - see code [here](https://github.com/Neuroling/SPINCO_SINEEG/blob/f4d9448b12b8cb8a548547862e8f34d1d758ab6f/Analysis/SiN/EEG/3_analysis_SMeier/PreStim_functions.py#L282). Unfortunately, this package does not allow accounting for multilevel data in logistic regression. 

For `statsmodels`' [mixed linear model](https://www.statsmodels.org/stable/generated/statsmodels.formula.api.mixedlm.html) you can pass the parameter `groups = "subjID"` (which I did before when still running linear mixed models [here](https://github.com/Neuroling/SPINCO_SINEEG/blob/f4d9448b12b8cb8a548547862e8f34d1d758ab6f/Analysis/SiN/EEG/3_analysis_SMeier/PreStim_functions.py#L193)). However, when doing the same with the [logit regression](https://www.statsmodels.org/stable/generated/statsmodels.formula.api.logit.html), I get an `Unknown kwargs "groups"` error. 

I cannot find a package that allows multilevel logistic regressions in python. I think the next thing I would try is looking at the sourcecode of statsmodels' mixed linear model and the logit regression. If I can find out how the mixed linear model accounts for multilevel data, I can create a function that incorporates that into the logit regression.

**Comment by samuelmull** [comment]
## Update: Circumventing the issue by analysing the data within-subject

I just talked to Alexis and we decided it would be better to circumvent the issue by running the logistic regression within-subject, rather than spending another couple of days on making it work with multilevel data.

Closing this issue now.

**Comment by ckwalters** [comment]
Hi Samuel, I apologize for jumping in to your repo but I was searching for ways to do multilevel logistic regression for my own neuroscience phd research. I'm curious whether you considered using the statsmodels [mixed effect binomial GLM ](https://www.statsmodels.org/stable/generated/statsmodels.genmod.bayes_mixed_glm.BinomialBayesMixedGLM.html). Another option I found was [bambi](https://bambinos.github.io/bambi/notebooks/hierarchical_binomial_bambi.html).

**Comment by samuelmull** [comment]
Update: The error in importing lmer from the pymer4 package was due to a capitalization mistake on my part. 
`from pymer4.models import Lmer` is the correct way to import the package.
A big thank you to @ejolly for pointing this out (see mention above).

On another note, @ckwalters , thank you for your comment! Sorry I didn't answer, I completely missed it.
